server:
  port: 8081
  servlet:
    context-path: /pay
## Mybatis
mybatis:
  mapper-locations: classpath:spring/sqlmap/*.xml
  type-aliases-package: com.example.pay.model

spring:
  datasource:
    #    url: jdbc:mysql://localhost:3307/mag?characterEncoding=utf-8
    url: jdbc:sqlite::resource:db/mag.db
    username: root
    password: root
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.sqlite.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 20
      initialSize: 1
      maxWait: 6000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
  thymeleaf:
    cache: false
#  quartz:
#    jdbc:
#      comment-prefix: QRTZ_
#    job-store-type: jdbc
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      retries: 0
#      batch-size: 16348
#      buffer-memory: 33554432
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: test-consumer-group
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      auto-commit-interval: 100
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
